# Generated by Django 5.2.13 on 2026-04-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50)),
                ('familiya', models.CharField(max_length=50)),
                ('yosh', models.PositiveIntegerField(blank=True, default=15)),
                ('picture', models.ImageField(blank=True, default='images/default.jpg', upload_to='images/')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
